# Generated by Django 4.2.3 on 2023-07-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(),
        ),
    ]
