# Generated by Django 4.2.3 on 2023-07-17 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_postcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomments',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 20, 36, 44, 191459)),
        ),
    ]
