# Generated by Django 4.2.3 on 2023-07-17 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_postcomments_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomments',
            old_name='name',
            new_name='naam',
        ),
        migrations.AlterField(
            model_name='postcomments',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 20, 38, 27, 403914)),
        ),
    ]
